#!/bin/bash

ROOTDIR=$(cd $(dirname $0); pwd)
CMDSF=${ROOTDIR}/CMDSF
CJOBF=${ROOTDIR}/CJOBF

function help(){
	echo "help information"
	echo "-a \"job\"      append a new job"
	echo "-l            list all jobs"
    echo "-r n1[,n2]    remove job(s) by number"
	echo "-c            current job"
	echo "-e            empty job list"
	echo "-h            for help information"
}

function addjob(){
    WKDIR=$(pwd)
    sourcefile=$(echo $OPTARG | cut -d " " -f1)
    verson=$(echo $OPTARG | cut -d " " -f2)
    runoutf=runout.${verson}
    runerrf=runerr.${verson}
    echo ">> add job : deckbuild $WKDIR/$sourcefile"
    echo $WKDIR $sourcefile $runoutf $runerrf >> $CMDSF
}

function creatfile(){
    if [[ ! -e "$1" ]]; then
        touch $1
    fi
}

creatfile $CMDSF
creatfile $CJOBF

while getopts "a:lhr:ec" opt
do
	case $opt in
		a)
            addjob
		;;
		l)
            all=$(cat $CMDSF | wc -l)
            echo "Total $all job(s)"
            cat -n $CMDSF | sed '1s/$/ (running)/'
		;;
		r)
            num=$OPTARG
            sed -i "${num}d" $CMDSF
            # all=$(cat $CMDSF | wc -l)
            # if [[ "$num" -le "$all" ]]; then
                # sed -i "${num}d" $CMDSF
            # fi
		;;
		e)
			rm -f $CMDSF
			touch $CMDSF
            echo "Total 0 job(s)"
		;;
		c)
			cat $CJOBF
		;;
		h)
            help
		;;
		?)
			echo "-h option for help"
		;;
	esac
done
