#!/bin/bash

ROOTDIR=$(cd $(dirname $0); pwd)
CMDSF=${ROOTDIR}/CMDSF
CJOBF=${ROOTDIR}/CJOBF

function help(){
	echo "help information"
	echo "-a \"job\"        append a new job"
    echo "-i index \"job\"  insert job"
	echo "-l              list all jobs"
    echo "-r n1[,n2]      remove job(s) by number"
	echo "-c              current job"
	echo "-s              show current job runout"
	echo "-e              empty job list"
	echo "-h              for help information"
}

function addjob(){
    WKDIR=$(pwd)
    sourcefile=$(echo $OPTARG | cut -d " " -f1)
    verson=$(echo $OPTARG | cut -d " " -f2)
    runoutf=runout.${verson}
    runerrf=runerr.${verson}
    echo ">> add job : deckbuild $WKDIR/$sourcefile"
    echo $WKDIR $sourcefile $runoutf $runerrf >> $CMDSF
}

function insertjob(){
    WKDIR=$(pwd)
    num=$(echo ${OPTARG} | cut -d " " -f1)
    sourcefile=$(echo ${OPTARG} | cut -d " " -f2)
    verson=$(echo ${OPTARG} | cut -d " " -f3)
    runoutf=runout.${verson}
    runerrf=runerr.${verson}
    echo "Insert job to position ${num}: deckbuild $WKDIR/$sourcefile"
    sed -i "${num}i ${WKDIR} ${sourcefile} ${runoutf} ${runerrf}" $CMDSF
}

function showrunout(){
    WKDIR=$(cat $CJOBF | cut -d ' ' -f1)
    RUNOUT=$(cat $CJOBF | cut -d ' ' -f3)
    cat ${WKDIR}/runoutd/${RUNOUT}
}

function creatfile(){
    if [[ ! -e "$1" ]]; then
        touch $1
    fi
}

creatfile $CMDSF
creatfile $CJOBF

while getopts "a:i:lhr:ecs" opt
do
	case $opt in
		a)
            addjob
		;;
        i)
            insertjob
        ;;
		l)
            all=$(cat $CMDSF | wc -l)
            echo "Total $all job(s)"
            cat -n $CMDSF | sed '1s/$/ (running)/'
		;;
		r)
            num=$OPTARG
            sed -i "${num}d" $CMDSF
		;;
		e)
			rm -f $CMDSF
			touch $CMDSF
            echo "Total 0 job(s)"
		;;
		c)
			cat $CJOBF
		;;
        s)
            showrunout
        ;;
		h)
            help
		;;
		?)
			echo "-h option for help"
		;;
	esac
done
