#!/bin/bash

ROOTDIR=$(cd $(dirname $0); pwd)
CMDSF=${ROOTDIR}/CMDSF
CJOBF=${ROOTDIR}/CJOBF

function excutejob(){
    rundir=$1
    sourcefile=$2
    runoutd=runoutd
    runoutf=${runoutd}/$3
    runerrf=${runoutd}/$3
    runlogf=${runoutd}/runlog.all

    cd $rundir
    
    if [[ ! -d "$runoutd" ]]; then
        mkdir $runoutd
    fi

    # echo "---------------------" $(date "+%Y-%m-%d %H:%M:%S") "---------------------" >> $runlogf
    silog -s -i "deckbuild -run -ascii $sourcefile -outfile $runoutf 2>> $runerrf" -f $runlogf
    deckbuild -run -ascii $sourcefile -outfile $runoutf 2>> $runerrf
    silog -d -i "deckbuild -run -ascii $sourcefile -outfile $runoutf 2>> $runerrf" -f $runlogf

    cd $ROOTDIR
}

function popjob(){
    sed -i '1d' $CMDSF
}

function printjob(){
    rundir=$1
    sourcefile=$2
    runoutd=runoutd
    runoutf=${runoutd}/$3
    runerrf=${runoutd}/$3
    runlogf=${runoutd}/runlog.all

    echo "=============================="
    echo "sourcefile is $sourcefile"
    echo "rundir     is $rundir"
    echo "runoutd    is $runoutd"
    echo "runoutf    is $runoutf"
    echo "runerrf    is $runerrf"
    echo "runlogf    is $runlogf"
}

while true
do
    sed -n '1p' $CMDSF > $CJOBF
    job=$(cat $CJOBF)
	if [[ -n $job ]]; then
        printjob $job
        popjob
		sleep 3
	else
		sleep 3
	fi
done
